name: Release Go project

on:
  push:
    tags:
      - "v*.*.*" # triggers only if push new tag version, like `0.8.4` or else

jobs:
  build:
    name: GoReleaser build
    runs-on: ubuntu-latest

    steps:
      - name: Check out goreleaser.yaml
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # See: https://goreleaser.com/ci/actions/

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          repository: amidaware/rmmagent
          ref: ${{github.ref_name}}
          path: rmmagent
          fetch-depth: 0 # See: https://goreleaser.com/ci/actions/

      - name: Set up Go 1.18
        uses: actions/setup-go@v3
        with:
          go-version: '1.18.3'
        id: go

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@master
        with:
          version: latest
          args: release --rm-dist
          workdir: rmmagent
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
